### ISSUE TITLE
Slashdot Dark for greasemonkey

### ISSUE THREAD

**Issue by lewisdonofrio** [cswarth/greasemonkey.scripts#1]
Do you have a script that I could use to make slashdot dark, I like your first script and was hoping you had moar ;)

**Comment by cswarth** [comment]
I don't have a script for that, but  I found the link below that uses the Stylish plug-in. It looks like it might do just what you're looking for.

https://userstyles.org/styles/23516/midnight-surfing-global-dark-style

**Comment by lewisdonofrio** [comment]
How do I convert stylish script to tampermonkey?

**Comment by cswarth** [comment]
I don't think you can - I would just install the stylish extension and use that instead.  It looks like people have contributed dark styles for a whole bunch of sites, including slashdot.org.

**Comment by lewisdonofrio** [comment]
I do not have stylish on edge ;(

**Comment by lewisdonofrio** [comment]
I guess the userstyle.org site allows you to do "Install style as userscript" and it works perfectly, closing issue now.
